CREATE SCHEMA `service` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'service'@'%' IDENTIFIED BY 'Secret*123';
GRANT ALL PRIVILEGES ON service.* TO 'service'@'%';
FLUSH PRIVILEGES;
